# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=50)),
                ('num_available', models.IntegerField(default=0)),
                ('num_rented', models.IntegerField(default=0)),
                ('date_last_rented', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
