# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tool_rental', '0002_auto_20170321_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='price',
        ),
        migrations.AddField(
            model_name='tool',
            name='day_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='month_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='week_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tool',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 19, 30, 55, 941986, tzinfo=utc)),
        ),
    ]
