# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tool_rental', '0004_auto_20170322_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 20, 3, 35, 637542, tzinfo=utc)),
        ),
    ]
