# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool_rental', '0005_auto_20170322_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='day_price',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='month_price',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='tool_descrip',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='week_price',
        ),
    ]
